name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v3

    - name: 🔑 Login to GitHub Container Registry
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: 🛠 Install Docker-Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose  # ✅ Add sudo
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose  # ✅ Add sudo

    - name: 📤 Pull Latest Docker Images
      run: |
        docker pull ghcr.io/vinaygs911/healthcare-backend:latest
        docker pull ghcr.io/vinaygs911/healthcare-frontend:latest
        docker pull ghcr.io/vinaygs911/healthcare-nginx:latest  # 🔥 ADDING NGINX IMAGE

    - name: 🚀 Deploy Using Docker Compose
      run: |
        docker compose down
        docker compose up -d
