name: NGINX CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push NGINX image
        run: |
          docker-compose -f docker-compose.yml build nginx
          docker-compose -f docker-compose.yml up -d nginx
